# Generated by Django 6.0.5 on 2026-05-09 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0019_remove_security_base_delete_historicalsecurity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalincidentpatient',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalincidentpatient',
            name='incident_ref',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='incident_ref',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='last_updated_user',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='historicaloperator',
            name='base',
        ),
        migrations.RemoveField(
            model_name='historicaloperator',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaloperator',
            name='role',
        ),
        migrations.RemoveField(
            model_name='historicalplace',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrole',
            name='history_user',
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ('command_weighting', 'base', 'name')},
        ),
        migrations.AlterField(
            model_name='incident',
            name='action_taken',
            field=models.TextField(blank=True, help_text='Briefly explain what has been done to address the incident situation. Provide as much detail as necessary.', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='cause_of_injury',
            field=models.TextField(blank=True, help_text='What was the cause of the injury?', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='effects_of_injury',
            field=models.TextField(blank=True, help_text='What are the signs/symptoms of the injury, other observations?', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='escalated_to',
            field=models.CharField(blank=True, help_text='Specify a 000 department, company, custodian, etc.', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='nature_of_injury',
            field=models.TextField(blank=True, help_text='What is the nature of the injury?', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='treatment_provided',
            field=models.TextField(blank=True, help_text='What treatment has been provided to the injury at this', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_entry_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalIncident',
        ),
        migrations.DeleteModel(
            name='HistoricalIncidentPatient',
        ),
        migrations.DeleteModel(
            name='HistoricalMessage',
        ),
        migrations.DeleteModel(
            name='HistoricalOperator',
        ),
        migrations.DeleteModel(
            name='HistoricalPlace',
        ),
        migrations.DeleteModel(
            name='HistoricalRole',
        ),
    ]
