# Generated by Django 6.0.5 on 2026-05-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0020_remove_historicalincidentpatient_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='callsign',
            field=models.CharField(blank=True, help_text='Callsign of the Base.', max_length=50, null=True),
        ),
    ]
