# Generated by Django 6.0.5 on 2026-05-16 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0021_place_callsign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('state', models.IntegerField(choices=[(1, 'Checked In'), (2, 'Checked Out')])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='float.place')),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='float.patrol')),
            ],
        ),
    ]
