# Generated by Django 6.0.5 on 2026-05-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0021_place_callsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address of the place.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude coordinate of the place.', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude coordinate of the place.', null=True),
        ),
    ]
