# Generated by Django 6.0.5 on 2026-05-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0022_place_address_place_latitude_place_longitude'),
        ('float', '0024_checkin_user'),
    ]

    operations = [
    ]
