# Generated by Django 6.0.5 on 2026-05-17 02:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0025_merge_20260516_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS coordinates of the location.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(blank=True, help_text='Address of the location, if known.', max_length=256, null=True),
        ),
    ]
